name: Client

on:
  pull_request:
    paths:
      - 'client/**'
  push:
    branches:
      - main
    paths:
      - 'client/**'

jobs:
  client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: cd client && cargo check --verbose
    - name: Run Lint
      run: cd client && cargo clippy -- -Dwarnings --verbose
    - name: Test
      run: cd client && cargo test --verbose
