
name: CI/CD

on: ['push', 'pull_request']

jobs:
  client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: cd client && cargo check
    - name: Run Lint
      run: cd server && cargo clippy -- -Dwarnings
    - name: Test
      run: cd server && cargo test
  server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: cd server && cargo check
    - name: Run Lint
      run: cd server && cargo clippy -- -Dwarnings
    - name: Test
      run: cd server && cargo test
